spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://1authority-interns.1rivet.com:5004
          jwkSeturi: https://1authority-interns.1rivet.com:5004/.well-known/openid-configuration/jwks
          audiences: DeskBookApi

server:
   port: 9443
   ssl: 
     enabled: true
     key-store-type: PKCS12
     key-store: file:C:\\deskbook-userapi\\deskbook.p12
     key-store-password: admin
     key-alias: dev-deskbook-userapi.1rivet.com

          
          
