spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://1authority-interns.1rivet.com:5004
          jwkSeturi: https://1authority-interns.1rivet.com:5004/.well-known/openid-configuration/jwks
          audiences: DeskBookApi

server:
   port: 8443
   ssl: 
     enabled: true
     key-store-type: PKCS12
     key-store: file:C:\\deskbook-userapi\\deskbook-userapi-dev.1rivet.com.p12
     key-store-password: admin
     key-alias: deskbook-userapi-dev.1rivet.com

          
          
